### ISSUE TITLE
use formatting to make command output clearer

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#26]
Oghliner's output is quite simplistic, just plain text without any special formatting. By contrast, other popular command-line tools, like Yeoman (`npm install -g yo && yo`), use color, boldness, and other stylistic formatting to clarify the text they output to the console. (Yeoman even prints ASCII art, although that's a bit extraneous.)

We should evaluate the output of the various Oghliner commands for opportunities to use formatting to make them clearer.
- [x] Use gutil.log to log messages (#131)
- [x] Print colored warnings and errors (#131)
- [x] Clarify output of `configure` (#148)
- [x] Print large file warning in yellow (#151)
- [x] Print all suggestions in blue (#156)
- [x] Clarify output of `bootstrap` (#160)
- [x] Clarify output of `integrate` (#161)
- [x] Clarify output of `offline` (#162)
- [x] Clarify output of `deploy` (#163)

**Comment by marco-c** [comment]
We should also improve error messages, using `console.error` doesn't give much details.

**Comment by marco-c** [comment]
#131 improves the situation.

**Comment by mykmelez** [comment]
It might be a bit further afield, but I see enhancements like #141 as keeping with the spirit of this issue.

**Comment by mykmelez** [comment]
All dependencies resolved, so this too is resolved!
